- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present

- name: Install packages.microsoft.com key
  apt_key:
    url: https://packages.microsoft.com/keys/microsoft.asc
    state: present

- name: Setup vscode repo
  apt_repository:
    repo: deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main
    state: present

- name: Install Visual Studio Code
  apt:
    name: code
    state: present
